services:
  db:
    image: postgres:15
    container_name: social_network_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: social_network
    ports:
      - "5432:5432"

  auth-service:
    build: ./back-auth
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  posts-service:
    build: ./back-posts
    ports:
      - "4001:4001"
    depends_on:
      - db
    environment:
      - DB_HOST=db